version: '3.9'
name: applicationname
services:
  api:
    build:
      context: ./ApplicationName-Api/
      dockerfile: ../ApplicationName-Api/Dockerfile
    ports:
      - 5001:443
    volumes:
      - ./Certificates:/https/:ro
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    user: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty1234!
      POSTGRES_DB: applicationname
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports:
      - 8080:8080