version: '3.9'
name: applicationname
services:
  api:
    build: ./ApplicationName-Api/
    ports:
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwerty1234!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./Certificates:/https/:ro
  db:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    user: root
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Qwerty1234!'
      ACCEPT_EULA: 'Y'
    volumes:
      - ./data/db:/var/opt/mssql/data
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '$$SA_PASSWORD' -Q 'SELECT 1' || exit 1
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s