version: '3.9'
name: applicationname
services:
  api:
    build:
      context: ./ApplicationName-Api/
      dockerfile: ../ApplicationName-Api/Dockerfile
    ports:
      - 5001:443
    volumes:
      - ./Certificates:/https/:ro