version: '3.9'
name: applicationname
services:
  api:
    build: ./ApplicationName-Api/
    ports:
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwerty1234!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./Certificates:/https/:ro