name: Publish to NuGet

on:
  release:
    types: [published]

env:
  NuGetDirectory: '${{github.workspace}}/.nuget'
  Version: ${{ github.event.release.tag_name }}

defaults:
  run:
    shell: pwsh

jobs:
  pack_nuget:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.0.0

    - name: dotnet pack
      run: dotnet pack src/Templates.WebApi.csproj -o ${{ env.NuGetDirectory }} -p:Version=${{ env.Version }}

    - uses: actions/upload-artifact@v4.3.0
      with:
        name: Templates.WebApi.${{ env.Version }}.nupkg
        if-no-files-found: error
        retention-days: 5
        path: ${{ env.NuGetDirectory }}/Templates.WebApi.${{ env.Version }}.nupkg
  
  publish_nuget:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ pack_nuget ]
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: Templates.WebApi.${{ env.Version }}.nupkg
          path: ${{ env.NuGetDirectory }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.0.0

      - name: Publish NuGet package
        run: dotnet nuget push ${{ env.NuGetDirectory }}/Templates.WebApi.${{ env.Version }}.nupkg --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json --skip-duplicate
