name: Publish to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    - name: Nuget pack
      run: nuget pack .\Templates.WebApi.nuspec -OutputDirectory .\.nuget -Version ${{ github.event.release.tag_name }}
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json
      
      
